// Copyright (C) Nexus contributors
// SPDX-License-Identifier: Apache-2.0

//! Autogenerated weights for `pallet-usdx`.
//!
//! Generated with Substrate benchmark CLI 53.0.0 on 2026-07-12 using 50 steps,
//! 20 repeats, compiled Wasm, max regression analysis and measured PoV mode.
//! 使用 Substrate benchmark CLI 53.0.0 于 2026-07-12 自动生成：50 steps、
//! 20 repeats、compiled Wasm、max 回归分析和 measured PoV 模式。

use core::marker::PhantomData;
use frame_support::{
    traits::Get,
    weights::{constants::RocksDbWeight, Weight},
};

/// Weight functions required by the USDX pallet.
/// USDX pallet 所需的权重函数。
pub trait WeightInfo {
    fn mint() -> Weight;
    fn redeem() -> Weight;
    fn register_collateral() -> Weight;
    fn set_enabled() -> Weight;
    fn set_paused() -> Weight;
    fn set_limits() -> Weight;
    fn set_policy() -> Weight;
    fn set_global_debt_ceiling() -> Weight;
    fn update_collateral() -> Weight;
    fn admin_credit_usdx() -> Weight;
}

/// Runtime DB-weight adapter generated from Nexus runtime benchmarks.
/// 由 Nexus runtime benchmark 生成的 runtime DB-weight adapter。
pub struct SubstrateWeight<T>(PhantomData<T>);

impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
    fn mint() -> Weight {
        Weight::from_parts(416_209_000, 10_524)
            .saturating_add(T::DbWeight::get().reads(22))
            .saturating_add(T::DbWeight::get().writes(9))
    }

    fn redeem() -> Weight {
        Weight::from_parts(475_833_000, 10_863)
            .saturating_add(T::DbWeight::get().reads(21))
            .saturating_add(T::DbWeight::get().writes(9))
    }

    fn register_collateral() -> Weight {
        Weight::from_parts(208_775_000, 7_290)
            .saturating_add(T::DbWeight::get().reads(9))
            .saturating_add(T::DbWeight::get().writes(6))
    }

    fn set_enabled() -> Weight {
        Weight::from_parts(206_465_000, 7_917)
            .saturating_add(T::DbWeight::get().reads(12))
            .saturating_add(T::DbWeight::get().writes(1))
    }

    fn set_paused() -> Weight {
        Weight::from_parts(40_927_000, 3_858)
            .saturating_add(T::DbWeight::get().reads(1))
            .saturating_add(T::DbWeight::get().writes(1))
    }

    fn set_limits() -> Weight {
        Weight::from_parts(61_079_000, 3_858)
            .saturating_add(T::DbWeight::get().reads(1))
            .saturating_add(T::DbWeight::get().writes(3))
    }

    fn set_policy() -> Weight {
        Weight::from_parts(41_823_000, 3_858)
            .saturating_add(T::DbWeight::get().reads(1))
            .saturating_add(T::DbWeight::get().writes(1))
    }

    fn set_global_debt_ceiling() -> Weight {
        Weight::from_parts(28_480_000, 1_693)
            .saturating_add(T::DbWeight::get().reads(1))
            .saturating_add(T::DbWeight::get().writes(1))
    }

    fn update_collateral() -> Weight {
        Weight::from_parts(149_386_000, 4_336)
            .saturating_add(T::DbWeight::get().reads(5))
            .saturating_add(T::DbWeight::get().writes(2))
    }

    fn admin_credit_usdx() -> Weight {
        Weight::from_parts(80_000_000, 5_000)
            .saturating_add(T::DbWeight::get().reads(5))
            .saturating_add(T::DbWeight::get().writes(3))
    }
}

impl WeightInfo for () {
    fn mint() -> Weight {
        Weight::from_parts(416_209_000, 10_524)
            .saturating_add(RocksDbWeight::get().reads(22))
            .saturating_add(RocksDbWeight::get().writes(9))
    }
    fn redeem() -> Weight {
        Weight::from_parts(475_833_000, 10_863)
            .saturating_add(RocksDbWeight::get().reads(21))
            .saturating_add(RocksDbWeight::get().writes(9))
    }
    fn register_collateral() -> Weight {
        Weight::from_parts(208_775_000, 7_290)
            .saturating_add(RocksDbWeight::get().reads(9))
            .saturating_add(RocksDbWeight::get().writes(6))
    }
    fn set_enabled() -> Weight {
        Weight::from_parts(206_465_000, 7_917)
            .saturating_add(RocksDbWeight::get().reads(12))
            .saturating_add(RocksDbWeight::get().writes(1))
    }
    fn set_paused() -> Weight {
        Weight::from_parts(40_927_000, 3_858)
            .saturating_add(RocksDbWeight::get().reads(1))
            .saturating_add(RocksDbWeight::get().writes(1))
    }
    fn set_limits() -> Weight {
        Weight::from_parts(61_079_000, 3_858)
            .saturating_add(RocksDbWeight::get().reads(1))
            .saturating_add(RocksDbWeight::get().writes(3))
    }
    fn set_policy() -> Weight {
        Weight::from_parts(41_823_000, 3_858)
            .saturating_add(RocksDbWeight::get().reads(1))
            .saturating_add(RocksDbWeight::get().writes(1))
    }
    fn set_global_debt_ceiling() -> Weight {
        Weight::from_parts(28_480_000, 1_693)
            .saturating_add(RocksDbWeight::get().reads(1))
            .saturating_add(RocksDbWeight::get().writes(1))
    }
    fn update_collateral() -> Weight {
        Weight::from_parts(149_386_000, 4_336)
            .saturating_add(RocksDbWeight::get().reads(5))
            .saturating_add(RocksDbWeight::get().writes(2))
    }
    fn admin_credit_usdx() -> Weight {
        Weight::from_parts(80_000_000, 5_000)
            .saturating_add(RocksDbWeight::get().reads(5))
            .saturating_add(RocksDbWeight::get().writes(3))
    }
}
