#!/usr/bin/env bash
# EN: One-time setup for relay backup ops (dirs, gpg passphrase, env file).
# CN: Relay 备份运维一次性初始化（目录、GPG 口令、env 文件）。

set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OPS="$ROOT/relay-ops"
DATA="$OPS/data"
BACKUPS="$OPS/backups"
ENV_FILE="$OPS/relay-backup.env"
PASS_FILE="$OPS/backup.pass"
EXAMPLE="$ROOT/scripts/relay-backup.env.example"

log() { printf '[relay-ops-init] %s\n' "$*" >&2; }

mkdir -p "$DATA" "$BACKUPS"
chmod 700 "$OPS" "$DATA" "$BACKUPS"

if [[ ! -f "$PASS_FILE" ]]; then
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -base64 32 >"$PASS_FILE"
  else
    head -c 32 /dev/urandom | base64 >"$PASS_FILE"
  fi
  chmod 600 "$PASS_FILE"
  log "created GPG passphrase: $PASS_FILE"
else
  log "passphrase exists: $PASS_FILE"
fi

if [[ ! -f "$ENV_FILE" ]]; then
  cat >"$ENV_FILE" <<EOF
# Generated by relay-ops-init.sh — edit paths for production (/opt/nexchat-relay).
RELAY_DATA_DIR=$DATA
BACKUP_LATEST_FILE=$OPS/latest-backup.json
BACKUP_LOCAL_DIR=$BACKUPS
BACKUP_ENCRYPT=gpg
GPG_PASSPHRASE_FILE=$PASS_FILE
IPFS_API=http://127.0.0.1:5001
IPFS_PIN=1
BACKUP_KEEP_LOCAL=5
BACKUP_STOP_RELAY=0
# Production with systemd:
# BACKUP_STOP_RELAY=1
# RELAY_STOP_CMD='systemctl stop nexchat-relay'
# RELAY_START_CMD='systemctl start nexchat-relay'
EOF
  chmod 600 "$ENV_FILE"
  log "created env: $ENV_FILE"
else
  log "env exists: $ENV_FILE"
fi

log "next steps:"
log "  1) Start relay:  RELAY_DATA_DIR=$DATA npm run relay:server"
log "  2) Backup once:  ./scripts/relay-backup-run.sh"
log "  3) Install timer: see deploy/systemd/ (optional)"
