[dependencies]
frame-benchmarking = { workspace = true, optional = true }
frame-support = { workspace = true }
frame-system = { workspace = true }
orml-traits = { workspace = true }
parity-scale-codec = { workspace = true, features = ["derive", "max-encoded-len"] }
scale-info = { workspace = true, features = ["derive"] }
sp-runtime = { workspace = true }
zeitgeist-primitives = { workspace = true }
zrml-market-commons = { workspace = true }

env_logger = { workspace = true, optional = true }
orml-currencies = { workspace = true, optional = true }
orml-tokens = { workspace = true, optional = true }
pallet-balances = { workspace = true, optional = true }
pallet-timestamp = { workspace = true, optional = true }
pallet-treasury = { workspace = true, optional = true }
prediction-mock-runtime = { workspace = true, optional = true }
serde = { workspace = true, optional = true }
sp-core = { workspace = true, optional = true }
sp-io = { workspace = true, optional = true }
zrml-authorized = { workspace = true, optional = true }
zrml-combinatorial-tokens = { workspace = true, optional = true }
zrml-court = { workspace = true, optional = true }
zrml-global-disputes = { workspace = true, optional = true }
zrml-neo-swaps = { workspace = true, optional = true }
zrml-orderbook = { workspace = true, optional = true }
zrml-prediction-markets = { workspace = true, optional = true }

[dev-dependencies]
test-case = { workspace = true }
zrml-hybrid-router = { workspace = true, features = ["mock"] }

[features]
default = ["std"]
mock = [
    "env_logger/default",
    "orml-currencies/default",
    "orml-tokens/default",
    "pallet-balances/default",
    "pallet-timestamp/default",
    "pallet-treasury/default",
    "prediction-mock-runtime/default",
    "serde/default",
    "sp-core/default",
    "sp-io/default",
    "zeitgeist-primitives/mock",
    "zrml-combinatorial-tokens/default",
    "zrml-market-commons/default",
    "zrml-neo-swaps/default",
    "zrml-orderbook/default",
    "zrml-prediction-markets/default",
    "zrml-prediction-markets/mock",
    "zrml-authorized/default",
    "zrml-court/default",
    "zrml-global-disputes/default",
]
runtime-benchmarks = [
    "frame-benchmarking/runtime-benchmarks",
    "frame-support/runtime-benchmarks",
    "frame-system/runtime-benchmarks",
    "zrml-combinatorial-tokens/runtime-benchmarks",
    "pallet-treasury?/runtime-benchmarks",
    "zrml-prediction-markets/runtime-benchmarks",
]
std = [
    "frame-benchmarking?/std",
    "frame-support/std",
    "frame-system/std",
    "orml-traits/std",
    "parity-scale-codec/std",
    "scale-info/std",
    "sp-runtime/std",
    "zeitgeist-primitives/std",
    "zrml-market-commons/std",
]
try-runtime = [
    "frame-support/try-runtime",
]

[package]
authors = ["Zeitgeist PM <contact@zeitgeist.pm>"]
edition.workspace = true
license = "GPL-3.0-or-later"
name = "zrml-hybrid-router"
publish = false
version = "0.6.1"
