// Copyright (C) Polytope Labs Ltd.
// SPDX-License-Identifier: Apache-2.0

//! Autogenerated weights for `pallet_hyper_fungible_token`.
//!
//! Generated with Substrate benchmark CLI 53.0.0 on 2026-07-11 using 50 steps,
//! 20 repeats, compiled Wasm, max regression analysis and measured PoV mode.
//! 使用 Substrate benchmark CLI 53.0.0 于 2026-07-11 自动生成：50 steps、
//! 20 repeats、compiled Wasm、max 回归分析和 measured PoV 模式。

use core::marker::PhantomData;
use polkadot_sdk::frame_support::{
    traits::Get,
    weights::{constants::RocksDbWeight, Weight},
};

pub trait WeightInfo {
    fn send() -> Weight;
    fn register_token(c: u32) -> Weight;
    fn update_token(add: u32, remove: u32) -> Weight;
}

/// Runtime DB-weight adapter generated from Nexus runtime benchmarks.
/// 由 Nexus runtime benchmark 生成的 runtime DB-weight adapter。
pub struct SubstrateWeight<T>(PhantomData<T>);

impl<T: polkadot_sdk::frame_system::Config> WeightInfo for SubstrateWeight<T> {
    fn send() -> Weight {
        Weight::from_parts(402_384_000, 4_617)
            .saturating_add(T::DbWeight::get().reads(11))
            .saturating_add(T::DbWeight::get().writes(6))
    }

    fn register_token(c: u32) -> Weight {
        Weight::from_parts(62_132_534, 3_768)
            .saturating_add(Weight::from_parts(21_817_592, 0).saturating_mul(c.into()))
            .saturating_add(T::DbWeight::get().reads(3))
            .saturating_add(T::DbWeight::get().reads(u64::from(c)))
            .saturating_add(T::DbWeight::get().writes(1))
            .saturating_add(T::DbWeight::get().writes(3_u64.saturating_mul(c.into())))
            .saturating_add(Weight::from_parts(0, 2_475).saturating_mul(c.into()))
    }

    fn update_token(a: u32, r: u32) -> Weight {
        Weight::from_parts(99_106_196, 3_910)
            .saturating_add(Weight::from_parts(68_737_465, 0).saturating_mul(a.into()))
            .saturating_add(Weight::from_parts(43_299_100, 0).saturating_mul(r.into()))
            .saturating_add(T::DbWeight::get().reads(3))
            .saturating_add(T::DbWeight::get().reads(3_u64.saturating_mul(a.into())))
            .saturating_add(T::DbWeight::get().reads(2_u64.saturating_mul(r.into())))
            .saturating_add(T::DbWeight::get().writes(4_u64.saturating_mul(a.into())))
            .saturating_add(T::DbWeight::get().writes(3_u64.saturating_mul(r.into())))
            .saturating_add(Weight::from_parts(0, 5_096).saturating_mul(a.into()))
            .saturating_add(Weight::from_parts(0, 2_619).saturating_mul(r.into()))
    }
}

impl WeightInfo for () {
    fn send() -> Weight {
        Weight::from_parts(402_384_000, 4_617)
            .saturating_add(RocksDbWeight::get().reads(11))
            .saturating_add(RocksDbWeight::get().writes(6))
    }

    fn register_token(c: u32) -> Weight {
        Weight::from_parts(62_132_534, 3_768)
            .saturating_add(Weight::from_parts(21_817_592, 0).saturating_mul(c.into()))
            .saturating_add(RocksDbWeight::get().reads(3))
            .saturating_add(RocksDbWeight::get().reads(u64::from(c)))
            .saturating_add(RocksDbWeight::get().writes(1))
            .saturating_add(RocksDbWeight::get().writes(3_u64.saturating_mul(c.into())))
            .saturating_add(Weight::from_parts(0, 2_475).saturating_mul(c.into()))
    }

    fn update_token(a: u32, r: u32) -> Weight {
        Weight::from_parts(99_106_196, 3_910)
            .saturating_add(Weight::from_parts(68_737_465, 0).saturating_mul(a.into()))
            .saturating_add(Weight::from_parts(43_299_100, 0).saturating_mul(r.into()))
            .saturating_add(RocksDbWeight::get().reads(3))
            .saturating_add(RocksDbWeight::get().reads(3_u64.saturating_mul(a.into())))
            .saturating_add(RocksDbWeight::get().reads(2_u64.saturating_mul(r.into())))
            .saturating_add(RocksDbWeight::get().writes(4_u64.saturating_mul(a.into())))
            .saturating_add(RocksDbWeight::get().writes(3_u64.saturating_mul(r.into())))
            .saturating_add(Weight::from_parts(0, 5_096).saturating_mul(a.into()))
            .saturating_add(Weight::from_parts(0, 2_619).saturating_mul(r.into()))
    }
}
