[dependencies]
fixed = { workspace = true }
frame-benchmarking = { workspace = true, optional = true }
frame-support = { workspace = true }
frame-system = { workspace = true }
hydra-dx-math = { workspace = true }
log = { workspace = true }
orml-traits = { workspace = true }
parity-scale-codec = { workspace = true, features = ["derive", "max-encoded-len"] }
scale-info = { workspace = true, features = ["derive"] }
sp-runtime = { workspace = true }
typenum = { workspace = true }
zeitgeist-primitives = { workspace = true }
zrml-market-commons = { workspace = true }

# Mock

env_logger = { workspace = true, optional = true }
orml-currencies = { workspace = true, optional = true }
orml-tokens = { workspace = true, optional = true }
pallet-assets = { workspace = true, optional = true }
pallet-balances = { workspace = true, optional = true }
pallet-prediction-collateral = { workspace = true, optional = true }
pallet-prediction-control = { workspace = true, optional = true }
pallet-preimage = { workspace = true, optional = true }
pallet-scheduler = { workspace = true, optional = true }
pallet-timestamp = { workspace = true, optional = true }
pallet-treasury = { workspace = true, optional = true }
prediction-mock-runtime = { workspace = true, optional = true }
serde = { workspace = true, optional = true }
sp-api = { workspace = true, optional = true }
sp-core = { workspace = true, optional = true }
sp-io = { workspace = true, optional = true }
zrml-authorized = { workspace = true, optional = true }
zrml-combinatorial-tokens = { workspace = true, optional = true }
zrml-court = { workspace = true, optional = true }
zrml-global-disputes = { workspace = true, optional = true }
zrml-futarchy = { workspace = true, optional = true }
zrml-prediction-markets = { workspace = true, optional = true }
zrml-prediction-markets-runtime-api = { workspace = true, optional = true }

[dev-dependencies]
more-asserts = { workspace = true }
test-case = { workspace = true }
zrml-neo-swaps = { workspace = true, features = ["mock"] }

[features]
default = ["std"]
mock = [
    "orml-currencies/default",
    "orml-tokens/default",
    "pallet-assets/default",
    "pallet-balances",
    "pallet-prediction-collateral/default",
    "pallet-prediction-control/default",
    "pallet-preimage/default",
    "pallet-scheduler/default",
    "pallet-timestamp/default",
    "pallet-treasury/default",
    "prediction-mock-runtime/default",
    "sp-api/default",
    "sp-io/default",
    "zeitgeist-primitives/mock",
    "zrml-prediction-markets-runtime-api/default",
    "sp-core/default",
    "zrml-combinatorial-tokens/std",
    "zrml-combinatorial-tokens/mock",
    "zrml-combinatorial-tokens/default",
    "zrml-court/std",
    "zrml-authorized/std",
    "zrml-global-disputes/std",
    "zrml-futarchy/std",
    "zrml-prediction-markets/std",
    "zrml-prediction-markets/mock",
    "zrml-prediction-markets/default",
    "serde/default",
    "env_logger/default",
]
runtime-benchmarks = [
    "frame-benchmarking/runtime-benchmarks",
    "frame-support/runtime-benchmarks",
    "frame-system/runtime-benchmarks",
    "zrml-combinatorial-tokens/runtime-benchmarks",
    "pallet-treasury?/runtime-benchmarks",
    "zrml-prediction-markets?/runtime-benchmarks",
]
std = [
    "frame-benchmarking?/std",
    "frame-support/std",
    "frame-system/std",
    "orml-traits/std",
    "pallet-assets?/std",
    "pallet-prediction-collateral?/std",
    "pallet-prediction-control?/std",
    "pallet-preimage?/std",
    "pallet-scheduler?/std",
    "parity-scale-codec/std",
    "scale-info/std",
    "sp-runtime/std",
    "zeitgeist-primitives/std",
    "zrml-market-commons/std",
    "zrml-futarchy?/std",
]
try-runtime = [
    "frame-support/try-runtime",
]

[package]
authors = ["Zeitgeist PM <contact@zeitgeist.pm>"]
edition.workspace = true
license = "GPL-3.0-or-later"
name = "zrml-neo-swaps"
publish = false
version = "0.6.1"
